"""Generate codex/data/malecns_regions.py from the observed MaleCNS ROI vocabulary.

Descriptions are reused from Codex's own FAFB region table wherever the base
abbreviation matches, so nothing is invented. Bases FAFB doesn't have get a
curated label from standard MANC/MaleCNS nomenclature, or the raw token when
there is no confident expansion.
"""
import os, re, sys, duckdb
sys.stdout.reconfigure(encoding="utf-8")
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from codex.data.brain_regions import REGIONS as _ALL_REGIONS
from codex.data.malecns_roi_naming import ROI_RENAMES, to_codex_region

# brain_regions merges whatever this script generated last time, so subtract
# those keys to recover the FAFB-only baseline. Makes re-runs idempotent.
try:
    from codex.data.malecns_regions import MALECNS_REGIONS as _PREV
except ImportError:
    _PREV = {}
FAFB_REGIONS = {k: v for k, v in _ALL_REGIONS.items() if k not in _PREV}

# base abbreviation -> description, harvested from FAFB's own table
FAFB_BASES = {}
for k, (_sid, desc) in FAFB_REGIONS.items():
    b = k[:-2] if k.endswith(("_L", "_R")) else k
    FAFB_BASES.setdefault(b, desc)

# Standard MANC / MaleCNS names FAFB has no entry for.
CURATED = {
    "AB": "asymmetric body",
    "CA": "mushroom body → calyx",
    "PED": "mushroom body → pedunculus",
    "AL": "antennal lobe",
    "ANM": "abdominal neuromere",
    "INTTCT": "intermediate tectulum",
    "LTCT": "lower tectulum",
    "LEGNP": "leg neuropil",
    "MVAC": "medial ventral association center",
    "NTCT(UTCT-T1)": "neck tectulum",
    "WTCT(UTCT-T2)": "wing tectulum",
    "HTCT(UTCT-T3)": "haltere tectulum",
    "AL(L)": "antennal lobe",
    "A'L": "mushroom body → alpha' lobe",
    "AL_MB": "mushroom body → alpha lobe",
    "B'L": "mushroom body → beta' lobe",
    "BL": "mushroom body → beta lobe",
    "GL": "mushroom body → gamma lobe",
}
NERVES = {
    "ADMN", "ABN1", "ABN2", "ABN3", "ABN4", "ABNT", "CVN", "DMETAN", "DPRON",
    "MESOAN", "MESOLN", "METALN", "PDMN", "PRN", "PROAN", "PROCN", "PROLN",
    "VPRON",
}
VNC_BASES = {
    "ANM", "INTTCT", "LTCT", "LEGNP", "MVAC", "NTCT(UTCT-T1)",
    "WTCT(UTCT-T2)", "HTCT(UTCT-T3)", "CRN",
}
OPTIC_BASES = {"ME", "LO", "LOP", "LA", "AME", "OPTIC-UNSPECIFIED"}
MB_BASES = {"CA", "PED"}
CX_BASES = {"EB", "FB", "PB", "NO", "AB"}

SIDE_RE = re.compile(r"\((L|R)\)$")


def base_of(name):
    """Strip a trailing (L)/(R) and the T1/T2/T3 segment index."""
    b = SIDE_RE.sub("", name)
    # LegNp(T2) / mVAC(T3) -> LegNp / mVAC, but keep NTct(UTct-T1) intact
    if not b.startswith(("NTCT", "WTCT", "HTCT")):
        b = re.sub(r"\(T[123]\)$", "", b)
    return b


con = duckdb.connect("lab/malecns_v10.duckdb", read_only=True)
names = [r[0] for r in con.execute("SELECT neuropil FROM rois ORDER BY neuropil").fetchall()]
con.close()

entries, categories, skipped = {}, {}, []
next_id = -1000
for raw in names:
    key = to_codex_region(raw)
    if key in FAFB_REGIONS:
        # Same abbreviation as a FAFB region: reuse that entry, which has a real
        # mesh. Same structure, different animal.
        skipped.append(key)
        continue
    b = base_of(key)
    # disambiguate the mushroom body alpha lobe from the antennal lobe
    lookup_b = "AL_MB" if b == "MB-AL" else b
    desc = FAFB_BASES.get(b) or CURATED.get(lookup_b) or CURATED.get(b)
    if not desc:
        desc = raw
    # LegNp(T2)(L) -> "leg neuropil (T2)": the segment index is dropped by
    # base_of(), so put it back into the human-readable label.
    seg = re.search(r"\(T[123]\)", key)
    if seg and not key.startswith(("NTCT", "WTCT", "HTCT")):
        desc = f"{desc} ({seg.group(0).strip('()')})"
    entries[key] = [next_id, desc]
    next_id -= 1

    if b.startswith("MB-"):
        cat = "MaleCNS mushroom body"
    elif b in NERVES:
        cat = "MaleCNS nerves"
    elif b in VNC_BASES or key.startswith("VNC-") or key.startswith("CV-"):
        cat = "MaleCNS ventral nerve cord"
    elif b in OPTIC_BASES:
        cat = "MaleCNS optic lobe"
    elif b in MB_BASES:
        cat = "MaleCNS mushroom body"
    elif b in CX_BASES:
        cat = "MaleCNS central complex"
    elif "UNSPECIFIED" in key:
        cat = "MaleCNS unspecified"
    else:
        cat = "MaleCNS central brain"
    categories.setdefault(cat, []).append(key)

with open("codex/data/malecns_regions.py", "w", encoding="utf-8", newline="\n") as f:
    f.write('"""MaleCNS v1.0 brain/VNC regions, merged into REGIONS by brain_regions.py.\n\n')
    f.write("Generated by lab/gen_malecns_regions.py from the ROI vocabulary actually\n")
    f.write("observed in the MaleCNS synapse table. Segment ids are negative, which is\n")
    f.write("Codex's existing convention for regions with no FlyWire mesh to draw --\n")
    f.write("url_for_neuropils() filters them out of the 3D mesh layer.\n\n")
    f.write("Regions whose abbreviation already exists in the FAFB table are deliberately\n")
    f.write("absent here and reuse the FAFB entry:\n")
    f.write("    " + ", ".join(sorted(skipped)) + "\n\"\"\"\n\n")
    f.write("MALECNS_REGIONS = {\n")
    for k, v in entries.items():
        f.write(f"    {k!r}: [{v[0]}, {v[1]!r}],\n")
    f.write("}\n\nMALECNS_REGION_CATEGORIES = {\n")
    for c, ks in categories.items():
        f.write(f"    {c!r}: [\n")
        for k in ks:
            f.write(f"        {k!r},\n")
        f.write("    ],\n")
    f.write("}\n")

print(f"{len(entries)} MaleCNS-specific regions, {len(skipped)} reuse FAFB entries")
for c, ks in categories.items():
    print(f"  {c:34} {len(ks)}")
print(f"reused from FAFB: {', '.join(sorted(skipped))}")
